### PR TITLE
Carthage support and restructuring

### PR DESCRIPTION
**Pull request by infinisil**
This adds carthage support and restructures the project to enable this. There is an actual framework target now. The demo app is a subproject of the main project. The tests are running on OS X now, which doesn't require the simulator to be started.

### CODE REVIEW

**Comment by radex** [comment]
Great work, this is much better! Thanks @Infinisil for contributing!

(There was a problem with the demo app, it wouldn't compile and work correctly, but i fixed that.)

**Comment by infinisil** [comment]
I’m glad I could help :D

**Comment by Kametrixom** [comment]
Ohh, one thing you need to do still. Somehow tags don't get pulled I just found out, but for Carthage to work you need a tagged release. To do this just

    git tag -a v1.0 -m "Version 1.0"

And push

**Comment by radex** [comment]
Done, thanks @Kametrixom ! https://github.com/radex/DiffyTables/releases

**Pull request merged**
